import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { SocialPostCard } from "@/components/social-post-card";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, Sparkles, Calendar, Send, Loader2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";

const postSchema = z.object({
  caption: z.string().min(1, "Caption is required"),
  platforms: z.array(z.string()).min(1, "Select at least one platform"),
  scheduledFor: z.string().optional(),
});

type PostFormData = z.infer<typeof postSchema>;

interface Post {
  id: string;
  caption: string;
  platforms: string[];
  createdAt: string;
  status: "draft" | "scheduled" | "published";
  scheduledFor?: string;
}

export default function UserSocial() {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [aiTopic, setAiTopic] = useState("");
  const { toast } = useToast();

  const { data: postsData, isLoading } = useQuery<{ posts: Post[] }>({
    queryKey: ["/api/posts"],
  });

  const form = useForm<PostFormData>({
    resolver: zodResolver(postSchema),
    defaultValues: {
      caption: "",
      platforms: [],
      scheduledFor: "",
    },
  });

  const createPostMutation = useMutation({
    mutationFn: async (data: PostFormData) => {
      const status = data.scheduledFor ? "scheduled" : "published";
      return await apiRequest("POST", "/api/posts", { ...data, status });
    },
    onSuccess: () => {
      toast({
        title: "Post created successfully",
        description: "Your post has been created",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/posts"] });
      setIsDialogOpen(false);
      form.reset();
      setAiTopic("");
    },
    onError: (error: any) => {
      toast({
        title: "Failed to create post",
        description: error.message || "Something went wrong",
        variant: "destructive",
      });
    },
  });

  const generateAIMutation = useMutation({
    mutationFn: async (context: string) => {
      const response = await apiRequest("POST", "/api/ai/generate-caption", { context });
      return response as unknown as { caption: string };
    },
    onSuccess: (data) => {
      form.setValue("caption", data.caption);
      toast({
        title: "AI Caption Generated",
        description: "Caption has been generated by AI",
      });
    },
    onError: (error: any) => {
      toast({
        title: "AI Generation Failed",
        description: error.message || "Failed to generate AI content. Make sure OPENAI_API_KEY is configured.",
        variant: "destructive",
      });
    },
  });

  const handleAISuggest = () => {
    const topic = aiTopic.trim() || "investment opportunities and wealth building";
    generateAIMutation.mutate(topic);
  };

  const handleSubmit = (data: PostFormData) => {
    createPostMutation.mutate(data);
  };

  const posts = postsData?.posts || [];

  const connectedAccounts = [
    { platform: "facebook", connected: true },
    { platform: "instagram", connected: true },
    { platform: "linkedin", connected: true },
    { platform: "tiktok", connected: false },
    { platform: "twitter", connected: true },
  ];

  const selectedPlatforms = form.watch("platforms");

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-bold font-serif mb-2">Social Media</h1>
          <p className="text-muted-foreground">Manage your social media presence</p>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button data-testid="button-create-post">
              <Plus className="h-4 w-4 mr-2" />
              Create Post
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl">
            <Form {...form}>
              <form onSubmit={form.handleSubmit(handleSubmit)}>
                <DialogHeader>
                  <DialogTitle>Create Social Media Post</DialogTitle>
                  <DialogDescription>
                    Write and schedule posts across multiple platforms
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4 py-4">
                  <div className="space-y-2">
                    <div className="space-y-2 rounded-md border p-3 bg-muted/30">
                      <FormLabel className="text-sm">AI Caption Generator</FormLabel>
                      <div className="flex gap-2">
                        <Input
                          placeholder="Enter a topic (e.g., 'stock market trends')"
                          value={aiTopic}
                          onChange={(e) => setAiTopic(e.target.value)}
                          data-testid="input-ai-topic"
                          className="flex-1"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          onClick={handleAISuggest}
                          disabled={generateAIMutation.isPending}
                          data-testid="button-ai-suggest"
                        >
                          {generateAIMutation.isPending ? (
                            <Loader2 className="h-4 w-4 animate-spin" />
                          ) : (
                            <Sparkles className="h-4 w-4" />
                          )}
                          <span className="ml-1 hidden sm:inline">
                            {generateAIMutation.isPending ? "Generating..." : "Generate"}
                          </span>
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Leave empty for a general investment-focused caption
                      </p>
                    </div>
                    <FormField
                      control={form.control}
                      name="caption"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Post Caption</FormLabel>
                          <FormControl>
                            <Textarea
                              placeholder="What's on your mind?"
                              rows={6}
                              data-testid="textarea-caption"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <FormField
                    control={form.control}
                    name="platforms"
                    render={() => (
                      <FormItem>
                        <FormLabel>Select Platforms</FormLabel>
                        <div className="space-y-2">
                          {["facebook", "instagram", "linkedin", "twitter", "tiktok"].map((platform) => (
                            <FormField
                              key={platform}
                              control={form.control}
                              name="platforms"
                              render={({ field }) => (
                                <FormItem className="flex flex-row items-center space-x-2 space-y-0">
                                  <FormControl>
                                    <Checkbox
                                      checked={field.value?.includes(platform)}
                                      onCheckedChange={(checked) => {
                                        const newValue = checked
                                          ? [...(field.value || []), platform]
                                          : field.value?.filter((p: string) => p !== platform) || [];
                                        field.onChange(newValue);
                                      }}
                                      data-testid={`checkbox-${platform}`}
                                    />
                                  </FormControl>
                                  <FormLabel className="text-sm font-medium capitalize leading-none cursor-pointer">
                                    {platform}
                                  </FormLabel>
                                </FormItem>
                              )}
                            />
                          ))}
                        </div>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
                <DialogFooter className="flex gap-2">
                  <Button
                    type="submit"
                    disabled={createPostMutation.isPending}
                    data-testid="button-post-now"
                  >
                    <Send className="h-4 w-4 mr-2" />
                    {createPostMutation.isPending ? "Posting..." : "Post Now"}
                  </Button>
                </DialogFooter>
              </form>
            </Form>
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Connected Accounts</CardTitle>
          <CardDescription>Manage your social media connections</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-3 flex-wrap">
            {connectedAccounts.map((account) => (
              <Badge
                key={account.platform}
                variant={account.connected ? "default" : "outline"}
                className="capitalize"
              >
                {account.platform}
                {account.connected ? " ✓" : " (Disconnected)"}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      <div>
        <h2 className="text-2xl font-bold font-serif mb-4">Your Posts</h2>
        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3].map((i) => (
              <Card key={i}>
                <CardContent className="p-4 space-y-2">
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-3/4" />
                  <Skeleton className="h-4 w-1/2" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : posts.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {posts.map((post) => (
              <SocialPostCard
                key={post.id}
                {...post}
                platforms={post.platforms as any}
                onView={() => console.log(`View post ${post.id}`)}
                onEdit={() => console.log(`Edit post ${post.id}`)}
              />
            ))}
          </div>
        ) : (
          <Card>
            <CardContent className="flex items-center justify-center h-32">
              <p className="text-muted-foreground">
                No posts yet. Click "Create Post" to publish your first post.
              </p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
